### ISSUE TITLE
Example added for composables

### ISSUE THREAD

**Issue by CalebKester** [KareemDa/pnpm-monorepo-nuxt-3#1]
Hi,

Thank you for the very helpful article and repo on this. I was wondering if you could add an example on how to share composables to this repo and article..

Thanks,

**Comment by tjeneis** [comment]
@CalebKester I think the Module Author Guide from Nuxt can help you with that. Check this section: https://nuxt.com/docs/guide/going-further/modules#injecting-composables-with-addimports-and-addimportsdir

```
import { defineNuxtModule, addImports, createResolver } from '@nuxt/kit'

export default defineNuxtModule({
  setup(options, nuxt) {
    const resolver = createResolver(import.meta.url)

    addImports({
      name: 'useComposable', // name of the composable to be used
      as: 'useComposable', 
      from: resolver.resolve('runtime/composables/useComposable') // path of composable 
    })
  }
})
```

**Comment by KareemDa** [comment]
@CalebKester Glad that you find it Helpful! 
I've updated the README file and added the original article for this repo.

Also, @tjeneis thank you for answering! this is exactly how to import `composables`

**Comment by CalebKester** [comment]
Thank you! I was digging around the Nuxt Kit part of the docs and missed that. This looks like it's exactly what I need!
